# ------------------------------------------------------------------------------------
#  File Rationale: Ruff Module TOML Configuration File.
#  Author: Stein
#
#  Creation Date: 2024-09-26T19:33-03:00
#  Last Modified at: 2024-09-26T19:33-03:00
# ------------------------------------------------------------------------------------

indent-width = 3

fix = true

[format]
docstring-code-format = true
docstring-code-line-length = 'dynamic'
exclude = [
	'.github',
	'.venv',
	'.vscode',
	'data',
	'docs',
	'*.md',
	'*.rst',
	'*.toml',
	'*.txt',
	'.gitignore',
	'.editorconfig'
]
indent-style = 'tab'
line-ending = "lf"
preview = false
quote-style = 'single'
skip-magic-trailing-comma = true
